# Generated by Django 3.0.2 on 2020-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=100)),
                ('sellerlocation', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=40)),
                ('imagefile', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
