# Generated by Django 3.1.1 on 2020-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0004_companyproductdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproductdetail',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
