# Generated by Django 3.1.1 on 2020-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0006_auto_20200911_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproductdetail',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='companyproductdetail',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
