# Generated by Django 3.1.1 on 2020-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0008_auto_20200911_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproductdetail',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
